import { useState } from 'react';
import { NavLink, Link } from 'react-router-dom';
import { Compass, LayoutDashboard, ArrowLeftRight, CreditCard, PieChart, Landmark, Target, BarChart3, Settings, Sparkles, MoreHorizontal, ArrowUpRight } from 'lucide-react';
import { Modal } from '@shared/ui';
const navigation = [
  { to: '/dashboard', label: 'Overview', icon: LayoutDashboard }, { to: '/transactions', label: 'Transactions', icon: ArrowLeftRight },
  { to: '/accounts', label: 'Accounts & cards', icon: CreditCard }, { to: '/budgets', label: 'Budgets', icon: PieChart },
  { to: '/loans', label: 'Loans & EMIs', icon: Landmark }, { to: '/goals', label: 'Goals', icon: Target },
  { to: '/reports', label: 'Reports & insights', icon: BarChart3 }, { to: '/ask-cfo', label: 'Ask CFO', icon: Sparkles }, { to: '/settings', label: 'Settings', icon: Settings },
];
export function Sidebar() { return <aside className="desktop-sidebar"><Link to="/dashboard" className="brand"><span className="brand-mark"><Compass size={24} strokeWidth={1.7} /></span><span>WealthPilot<span className="brand-caption">A little clarity goes a long way.</span></span></Link><div className="nav-caption">YOUR WORKSPACE</div><nav aria-label="Main navigation" className="space-y-1.5">{navigation.map(item => <NavLink key={item.to} to={item.to} className={({ isActive }) => 'sidebar-link ' + (isActive ? 'active' : '')}><item.icon size={19} strokeWidth={1.7} /><span>{item.label}</span>{item.to === '/ask-cfo' && <span className="ml-auto rounded bg-indigo-100 px-1.5 py-0.5 text-[9px] font-bold text-indigo-900">AI</span>}</NavLink>)}</nav><div className="sidebar-cfo"><span className="mb-3 inline-flex rounded-lg bg-white/15 p-2"><Sparkles size={18} /></span><p className="font-semibold">Big decision?<br />Start with a clear plan.</p><p className="mb-4 mt-2 text-xs leading-relaxed text-indigo-100">Your personal CFO helps you see what a purchase means for your future.</p><Link to="/ask-cfo" className="flex items-center justify-between rounded-lg bg-white px-3 py-2 text-xs font-semibold text-indigo-950">Let’s talk <ArrowUpRight size={15} /></Link></div><p className="sidebar-footer"><span className="mr-2 inline-block h-1.5 w-1.5 rounded-full bg-emerald-500" />Demo workspace · INR</p></aside>; }
export function MobileNavigation() { const [more, setMore] = useState(false); const primary = navigation.filter(item => ['/dashboard', '/transactions', '/goals', '/ask-cfo'].includes(item.to)); return <><nav aria-label="Mobile navigation" className="mobile-navigation">{primary.map(item => <NavLink key={item.to} to={item.to} className={({ isActive }) => 'mobile-nav-item ' + (isActive ? 'active' : '')}><item.icon size={20} /><span>{item.to === '/dashboard' ? 'Home' : item.label}</span></NavLink>)}<button className="mobile-nav-item" type="button" aria-label="More navigation" aria-expanded={more} onClick={() => setMore(true)}><MoreHorizontal size={21} /><span>More</span></button></nav><Modal title="Your workspace" open={more} onClose={() => setMore(false)}><nav aria-label="Additional navigation" className="grid gap-2">{navigation.map(item => <NavLink key={item.to} to={item.to} onClick={() => setMore(false)} className="flex min-h-12 items-center gap-3 rounded-lg px-3 text-sm text-ink hover:bg-canvas"><item.icon size={18} />{item.label}</NavLink>)}</nav></Modal></>; }
