import { Smartphone, Laptop, Plane, Headphones, Sparkles, CheckCircle2 } from 'lucide-react';
import type { ReactNode } from 'react';
import { Badge, Card, ProgressBar } from '@shared/ui';
import { formatMoney, formatDate } from '@shared/lib';
import { goalProgress, remainingForGoal, type GoalAffordability } from '../model/selectors';
import type { Goal } from '../model/types';
export function GoalCard({ goal, affordability, estimatedDate, action }: { goal: Goal; affordability: GoalAffordability; estimatedDate?: string | null; action?: ReactNode }) {
  const Icon = { phone: Smartphone, laptop: Laptop, plane: Plane, headphones: Headphones, sparkles: Sparkles }[goal.icon];
  return <Card className={goal.status === 'achieved' ? 'border-emerald-300 dark:border-emerald-800' : ''}><div className="mb-5 flex items-start justify-between gap-3"><span className="flex h-14 w-14 items-center justify-center overflow-hidden rounded-2xl bg-indigo-50 text-indigo-700 dark:bg-indigo-950 dark:text-indigo-200">{goal.imageUrl ? <img src={goal.imageUrl} alt="" className="h-full w-full object-cover" loading="lazy" /> : <Icon size={25} aria-hidden="true" />}</span><Badge tone={affordability.tone}>{affordability.label}</Badge></div><h3 className="text-lg font-semibold text-ink">{goal.name}</h3><p className="mt-1 text-xs text-muted">{goal.priority} priority{goal.targetDate ? ' · Target ' + formatDate(goal.targetDate) : ''}</p><div className="mb-2 mt-6 flex items-baseline justify-between"><span className="text-xl font-semibold text-ink">{formatMoney(goal.savedPaise)}</span><span className="text-sm text-muted">of {formatMoney(goal.targetPaise)}</span></div><ProgressBar value={goalProgress(goal)} label={goal.name + ' savings progress'} tone={goal.status === 'saving' ? 'brand' : 'positive'} /><p className="mt-3 text-xs text-muted">{goal.status === 'purchased' ? 'Purchased ' + formatDate(goal.purchasedAt ?? goal.createdAt) : remainingForGoal(goal) === 0 ? 'Fully funded. Your goal is ready.' : formatMoney(remainingForGoal(goal)) + ' to go' + (estimatedDate ? ' · Saving estimate ' + formatDate(estimatedDate) : '')}</p>{goal.status === 'achieved' && <p className="mt-3 flex items-center gap-2 text-sm text-[var(--positive)]"><CheckCircle2 size={16} aria-hidden="true" />You reached your goal!</p>}<p className="mt-3 text-xs leading-relaxed text-muted">{affordability.reason}</p>{action && <div className="mt-5">{action}</div>}</Card>;
}
