import { useEffect, useState } from 'react';
import { useGoalPlan } from '@entities/goal';
import { overviewApi } from '@entities/overview';
import { useCategories, categoryName } from '@entities/category';
import type { ReportView } from '@shared/api';
import { DEMO_MONTH } from '@shared/config';
import { formatMoney, formatDate, errorMessage } from '@shared/lib';
import { PageHeader, Card, Select, Input, Button, AsyncState, CartesianChart, ChartDataTable, ProgressBar, type ChartSeries } from '@shared/ui';
const series: ChartSeries[] = [{ key: 'incomePaise', label: 'Income', color: '#059669' }, { key: 'expensePaise', label: 'Expenses', color: '#e11d48' }];
export function ApiReports() { const [period, setPeriod] = useState<'month' | 'year'>('month'); const [value, setValue] = useState(DEMO_MONTH); const [report, setReport] = useState<ReportView | null>(null); const [error, setError] = useState<string | null>(null); const [retry, setRetry] = useState(0); const categories = useCategories(); const financialVersion = useGoalPlan(s => s.version);
 useEffect(() => { const controller = new AbortController(); setReport(null); setError(null); void overviewApi.report(period, value, { signal: controller.signal }).then(result => { if (!controller.signal.aborted) setReport(result); }).catch((cause: unknown) => { if (!controller.signal.aborted) setError(errorMessage(cause)); }); return () => controller.abort(); }, [period, value, retry, financialVersion]);
 const points = (report?.trends ?? []).map(point => ({ ...point, month: point.month ?? '', label: formatDate((point.month ?? DEMO_MONTH) + '-01', { month: 'short', year: '2-digit' }) }));
 const download = () => { if (!report) return; const rows = [['period','income_INR','expenses_INR','savings_INR'], [value,String(report.incomePaise/100),String(report.expensePaise/100),String(report.savingsPaise/100)]]; const blob = new Blob([rows.map(row => row.join(',')).join('\r\n')], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'wealthpilot-report-' + value + '.csv'; anchor.click(); URL.revokeObjectURL(url); };
 return <div className="space-y-6"><PageHeader eyebrow="THE PATTERNS BEHIND THE NUMBERS" title="Your financial picture." description="Complete totals and category trends for the period you choose." action={<Button variant="secondary" disabled={!report} onClick={download}>Export CSV</Button>} /><div className="flex flex-wrap gap-4"><Select label="Period" value={period} onChange={event => { const next = event.target.value as 'month' | 'year'; setPeriod(next); setValue(next === 'month' ? DEMO_MONTH : DEMO_MONTH.slice(0,4)); }}><option value="month">Monthly</option><option value="year">Yearly</option></Select><Input label={period === 'month' ? 'Month' : 'Year'} type={period === 'month' ? 'month' : 'number'} value={value} onChange={event => setValue(event.target.value)} /></div><AsyncState loading={!report} error={error} onRetry={() => setRetry(item => item + 1)}>{report && <><div className="grid gap-5 sm:grid-cols-3">{[['Income',report.incomePaise],['Expenses',report.expensePaise],['Net savings',report.savingsPaise]].map(([label,amount]) => <Card key={label}><p className="text-xs text-muted">{label}</p><p className="mt-3 text-2xl font-semibold text-ink">{formatMoney(Number(amount))}</p></Card>)}</div><p className="my-4 text-sm text-muted">Savings rate: {report.savingsRatePercent.toFixed(1)}% · {report.coverageFrom} to {report.coverageTo}</p><Card title="Income and expenses"><CartesianChart data={points} series={series} xKey="label" label="Report income and expense trend" formatValue={formatMoney} formatAxis={value => formatMoney(value, { compact: true })} /><ChartDataTable data={points} series={series} xKey="label" formatValue={formatMoney} caption="Complete report period" /></Card><Card title="Category spending" className="mt-6"><div className="space-y-4">{(report.categories ?? []).map(item => <div key={item.categoryId}><p className="mb-2 flex justify-between text-sm text-ink"><span>{categoryName(categories.items, item.categoryId ?? '')}</span><span>{formatMoney(item.amountPaise)}</span></p><ProgressBar value={report.expensePaise ? item.amountPaise/report.expensePaise*100 : 0} label="Share of expenses" /></div>)}</div></Card><Card title="Category trends" className="mt-6"><div className="overflow-auto"><table className="w-full text-left text-xs text-ink"><thead><tr><th className="p-2">Month</th><th className="p-2">Category</th><th className="p-2">Spending</th></tr></thead><tbody>{(report.categoryTrends ?? []).flatMap(point => (point.categories ?? []).map(item => ({ ...item, month: point.month }))).map((item,index) => <tr key={index}><td className="p-2">{item.month}</td><td className="p-2">{categoryName(categories.items,item.categoryId ?? '')}</td><td className="p-2">{formatMoney(item.amountPaise)}</td></tr>)}</tbody></table></div></Card></>}</AsyncState></div>;
}
