import { useEffect, useState } from 'react';
import { cardApi, useCards } from '@entities/card';
import { goalApi, useGoals } from '@entities/goal';
import { notificationApi } from '@entities/notification';
import { overviewApi } from '@entities/overview';
import { Card, Select, Button, AsyncState, EmptyState } from '@shared/ui';
import { formatMoney, errorMessage } from '@shared/lib';
export function FinancialHistory() { const [kind, setKind] = useState('notifications'); const [target, setTarget] = useState(''); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [rows, setRows] = useState<Record<string, unknown>[] | null>(null); const [error, setError] = useState<string | null>(null); const [revision, setRevision] = useState(0); const cards = useCards(); const goals = useGoals();
 useEffect(() => { const controller = new AbortController(); setRows(null); setError(null); const run = async () => { if ((kind === 'bills' || kind === 'contributions') && !target) { setRows([]); setTotal(0); return; } let data: unknown; if (kind === 'notifications') { const result = await notificationApi.history(page, 50, { signal: controller.signal }); data = result.items; setTotal(result.total); } else if (kind === 'reminders') data = await notificationApi.listReminders({ signal: controller.signal }); else if (kind === 'bills') data = await cardApi.bills(target, { signal: controller.signal }); else if (kind === 'contributions') data = await goalApi.contributions(target, { signal: controller.signal }); else data = [await overviewApi.summary({ signal: controller.signal })]; if (!controller.signal.aborted) setRows((Array.isArray(data) ? data : []).map(item => item as Record<string, unknown>)); }; void run().catch((cause: unknown) => { if (!controller.signal.aborted) setError(errorMessage(cause)); }); return () => controller.abort(); }, [kind,target,page,revision]);
 const resources = kind === 'bills' ? cards.items.filter(card => card.type === 'credit') : goals.items;
 const columns = kind === 'notifications' ? ['title','message','createdAt','read'] : kind === 'reminders' ? ['title','dueDate','createdAt'] : kind === 'bills' ? ['month','amountPaise','paidPaise','dueDate'] : kind === 'contributions' ? ['amountPaise','createdAt'] : ['month','liquidBalancePaise','creditCardDebtPaise','activeLoanOutstandingPaise','netWorthPaise','unallocatedSavingsPaise'];
 return <Card title="History and records"><div className="mb-5 flex flex-wrap gap-3"><Select label="Records" value={kind} onChange={event => { setKind(event.target.value); setTarget(''); setPage(1); }}><option value="notifications">Notification history</option><option value="reminders">Reminders</option><option value="bills">Credit card bills</option><option value="contributions">Goal contributions</option><option value="summary">Financial summary</option></Select>{(kind === 'bills' || kind === 'contributions') && <Select label={kind === 'bills' ? 'Credit card' : 'Goal'} value={target} onChange={event => setTarget(event.target.value)}><option value="">Choose</option>{resources.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</Select>}</div><AsyncState loading={!rows} error={error} onRetry={() => setRevision(value => value+1)}>{rows?.length ? <div className="overflow-auto"><table className="w-full text-left text-xs text-ink"><thead><tr>{columns.map(key => <th key={key} className="p-2">{key.replace(/Paise$/, ' (₹)').replace(/([A-Z])/g,' $1')}</th>)}</tr></thead><tbody>{rows.map((item,index) => <tr key={String(item.id ?? index)}>{columns.map(key => <td key={key} className="p-2">{key.endsWith('Paise') ? formatMoney(Number(item[key] ?? 0)) : typeof item[key] === 'boolean' ? item[key] ? 'Read' : 'Unread' : String(item[key] ?? '—')}</td>)}</tr>)}</tbody></table></div> : <EmptyState title="No records yet" description="Choose a record type or add your first entry." />}</AsyncState>{kind === 'notifications' && <div className="mt-4 flex justify-end gap-3"><Button variant="secondary" disabled={page <= 1} onClick={() => setPage(value => value-1)}>Previous</Button><Button variant="secondary" disabled={page*50 >= total} onClick={() => setPage(value => value+1)}>Next</Button></div>}</Card>;
}
