import { IS_DEMO } from '@shared/config';
import { CreditCard } from 'lucide-react';
import { formatDate, formatMoney } from '@shared/lib';
import { ProgressBar } from '@shared/ui';
import type { PaymentCard as PaymentCardModel } from '../model/types';
export function PaymentCard({ card }: { card: PaymentCardModel }) {
  const utilization = card.limitPaise ? card.balancePaise / card.limitPaise * 100 : 0;
  return <article className="overflow-hidden rounded-card border border-line bg-panel shadow-card"><div style={{ background: card.gradient.startsWith('linear-gradient(') ? card.gradient : 'linear-gradient(135deg, #172554, #4338ca)' }} className="relative min-h-48 overflow-hidden p-6 text-white"><div aria-hidden="true" className="absolute -right-8 -top-14 h-48 w-48 rounded-full border-[24px] border-white/10" /><div className="relative flex justify-between"><h3 className="font-semibold">{card.name}</h3><CreditCard size={23} aria-hidden="true" /></div><p className="relative mt-8 font-mono text-lg tracking-[.2em]">•••• •••• •••• {card.lastFour}</p><div className="relative mt-5 flex justify-between text-xs"><span className="uppercase tracking-widest">{card.type}{IS_DEMO ? ' · Demo' : ''}</span><span className="font-bold italic">{card.network}</span></div></div><div className="space-y-3 p-5"><div className="flex justify-between text-sm"><span className="text-muted">{card.type === 'credit' ? 'Outstanding' : 'Linked account balance'}</span><span className="font-semibold text-ink">{formatMoney(card.balancePaise)}</span></div>{card.type === 'credit' && <><ProgressBar value={utilization} label={card.name + ' credit utilization'} tone={utilization > 30 ? 'warning' : 'brand'} /><div className="flex justify-between text-xs text-muted"><span>{utilization.toFixed(0)}% utilized</span><span>Limit {formatMoney(card.limitPaise ?? 0)}</span></div><p className="text-xs text-muted">{formatMoney(card.duePaise ?? 0)} due {card.dueDate ? formatDate(card.dueDate) : '—'}</p></>}</div></article>;
}
