import { Link } from 'react-router-dom';
import { CalendarClock, TrendingUp, Landmark } from 'lucide-react';
import { Badge, ProgressBar } from '@shared/ui';
import { formatMoney, formatDate } from '@shared/lib';
import type { CfoRichCard as RichCard } from '../model/types';
export function CfoRichCard({ card }: { card: RichCard }) {
  const shell = 'rounded-xl border border-line bg-panel p-4';
  switch (card.kind) {
    case 'impact': return <section className={shell}><h4 className="mb-3 font-semibold text-ink">{card.title}</h4><dl className="grid grid-cols-2 gap-3 text-xs"><div><dt className="text-muted">Purchase price</dt><dd className="mt-1 font-semibold text-ink">{formatMoney(card.purchasePricePaise)}</dd></div><div><dt className="text-muted">Unallocated savings</dt><dd className="mt-1 font-semibold text-ink">{formatMoney(card.unallocatedSavingsPaise)}</dd></div></dl><div className="my-3"><Badge tone={card.emergencyTone}>{card.emergencyLabel}</Badge></div>{card.goalDelays.map(delay => <p key={delay.goalName} className="mb-2 text-xs text-muted">{delay.goalName}: estimated {delay.months}-month delay if you buy now</p>)}<p className="flex items-center gap-2 text-xs font-semibold text-ink"><CalendarClock size={14} aria-hidden="true" />Recommended review: {(card.recommendedBuyDate ? formatDate(card.recommendedBuyDate) : 'No safe date yet')}</p><p className="mt-3 text-xs leading-relaxed text-muted">{card.explanation}</p></section>;
    case 'loan-payoff': return <section className={shell}><h4 className="mb-3 flex items-center gap-2 font-semibold text-ink"><Landmark size={16} aria-hidden="true" />{card.title}</h4>{card.loans.map(loan => <div key={loan.name} className="mb-3 space-y-2 rounded-lg bg-canvas p-3 text-xs"><p className="font-semibold text-ink">{loan.name} · {formatMoney(loan.outstandingPaise)} remaining</p><dl className="grid grid-cols-2 gap-2"><div><dt className="text-muted">Current EMI</dt><dd className="mt-1 text-ink">{formatMoney(loan.emiPaise)}</dd></div><div><dt className="text-muted">Extra repayment</dt><dd className="mt-1 text-ink">{formatMoney(loan.extraPaise)}</dd></div><div><dt className="text-muted">Planned monthly total</dt><dd className="mt-1 font-semibold text-ink">{formatMoney(loan.monthlyPaymentPaise)}</dd></div><div><dt className="text-muted">Estimated payoff</dt><dd className="mt-1 text-ink">{loan.months === null ? 'Payment needs review' : loan.months + ' months'}{loan.payoffDate ? ' · ' + formatDate(loan.payoffDate) : ''}</dd></div></dl></div>)}<p className="text-xs leading-relaxed text-muted">{card.explanation}</p><Link to="/loans" className="mt-3 inline-block text-xs font-semibold text-indigo-700 underline dark:text-indigo-300">View loans and EMIs</Link></section>;
    case 'strategy': return <section className={shell}><h4 className="mb-3 font-semibold text-ink">{card.title}</h4><div className="space-y-3">{card.options.map(option => <div key={option.name} className="rounded-lg bg-canvas p-3"><p className="text-xs font-semibold text-ink">{option.name}{option.costPaise === undefined ? '' : ' · ' + formatMoney(option.costPaise)}</p><p className="mt-1 text-xs leading-relaxed text-muted">{option.description}</p></div>)}</div></section>;
    case 'roi': return <section className={shell}><h4 className="mb-3 flex items-center gap-2 font-semibold text-ink"><TrendingUp size={16} aria-hidden="true" />{card.title}</h4><dl className="grid grid-cols-2 gap-3 text-xs"><div><dt className="text-muted">Illustrative extra income</dt><dd className="mt-1 font-semibold text-ink">{formatMoney(card.potentialMonthlyIncomePaise)} / month</dd></div><div><dt className="text-muted">Estimated break-even</dt><dd className="mt-1 font-semibold text-ink">{card.breakEvenMonths} months</dd></div></dl><p className="mt-3 text-xs leading-relaxed text-muted">{card.explanation}</p></section>;
    case 'salary-growth': return <section className={shell}><h4 className="mb-3 font-semibold text-ink">{card.title}</h4><div className="mb-2 flex justify-between text-xs"><span className="text-muted">Current {formatMoney(card.currentSalaryPaise)}</span><span className="font-semibold text-ink">Target {formatMoney(card.targetSalaryPaise)}</span></div><ProgressBar value={card.progressPercent} label="Progress toward salary target" tone="positive" /><ul className="mt-3 list-disc space-y-1 pl-4 text-xs leading-relaxed text-muted">{card.steps.map(step => <li key={step}>{step}</li>)}</ul></section>;
  }
}
