import { Link } from 'react-router-dom';
import { ShieldCheck, CalendarClock, ArrowUpRight } from 'lucide-react';
import { useUser, emergencyFundHealth } from '@entities/user';
import { useCards } from '@entities/card';
import { useLoans } from '@entities/loan';
import { Card, AsyncState, ProgressBar, EmptyState, Badge } from '@shared/ui';
import { DEMO_TODAY } from '@shared/config';
import { formatDate, formatMoney } from '@shared/lib';
export function FinancialHealth() { const user = useUser(); const cards = useCards(); const loans = useLoans(); const bills = [...cards.items.filter(card => card.type === 'credit' && card.dueDate && card.dueDate >= DEMO_TODAY).map(card => ({ id: card.id, name: card.name, date: card.dueDate ?? DEMO_TODAY, amount: card.duePaise ?? 0, href: '/accounts' })), ...loans.items.filter(loan => loan.status === 'active').map(loan => ({ id: loan.id, name: loan.name + ' EMI', date: loan.nextDueDate, amount: loan.emiPaise, href: '/loans' }))].sort((a, b) => a.date.localeCompare(b.date)).slice(0, 3); return <div className="space-y-6"><Card title="Your safety net" action={<ShieldCheck size={18} className="text-emerald-600 dark:text-emerald-300" />}><AsyncState loading={!user.profile} error={user.error} onRetry={() => void user.load(true)}>{user.profile && <><div className="mb-3 flex items-baseline justify-between"><p className="text-2xl font-semibold text-ink">{formatMoney(user.profile.emergencyFundPaise)}</p><Badge tone={emergencyFundHealth(user.profile) >= 100 ? 'positive' : 'warning'}>{Math.round(emergencyFundHealth(user.profile))}% funded</Badge></div><ProgressBar value={emergencyFundHealth(user.profile)} label="Emergency fund health" tone="positive" /><p className="mt-3 text-xs leading-relaxed text-muted">Building toward {formatMoney(user.profile.emergencyTargetPaise)}. A buffer for life’s little surprises.</p><Link className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-indigo-700 dark:text-indigo-300" to="/settings">Review your target <ArrowUpRight size={14} /></Link></>}</AsyncState></Card><Card title="Coming up" action={<CalendarClock size={18} className="text-muted" />}><AsyncState loading={!cards.loaded || !loans.loaded} error={cards.error ?? loans.error} onRetry={() => { void cards.load(true); void loans.load(true); }}>{bills.length ? bills.map(bill => <Link key={bill.id} to={bill.href} className="flex items-center justify-between gap-3 border-b border-line py-4 first:pt-0 last:border-0 last:pb-0"><div><p className="text-sm font-medium text-ink">{bill.name}</p><p className="mt-1 text-xs text-muted">Due {formatDate(bill.date, { day: 'numeric', month: 'short' })}</p></div><span className="text-sm font-semibold tabular-nums text-ink">{formatMoney(bill.amount)}</span></Link>) : <EmptyState title="Nothing due soon" description="Enjoy a little breathing room." />}</AsyncState></Card></div>; }
