import { memo, useId } from 'react';
import { AreaChart, Area, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts';
export interface ChartSeries { key: string; label: string; color: string }
export type ChartPoint = Record<string, string | number>;
interface ChartProps { data: ChartPoint[]; series: ChartSeries[]; xKey: string; label: string; formatValue: (value: number) => string; formatAxis: (value: number) => string; variant?: 'area' | 'bar' }
const tick = { fill: 'rgb(var(--muted))', fontSize: 11 };
const tooltipStyle = { background: 'rgb(var(--panel))', color: 'rgb(var(--ink))', border: '1px solid rgb(var(--line))', borderRadius: 12, fontSize: 12 };
export const CartesianChart = memo(function CartesianChart({ data, series, xKey, label, formatValue, formatAxis, variant = 'area' }: ChartProps) {
  const id = useId().replaceAll(':', '');
  const axes = <><CartesianGrid stroke="rgb(var(--line))" strokeDasharray="3 5" vertical={false} /><XAxis dataKey={xKey} axisLine={false} tickLine={false} tick={tick} tickMargin={12} minTickGap={18} /><YAxis width={72} axisLine={false} tickLine={false} tick={tick} tickFormatter={formatAxis} /><Tooltip contentStyle={tooltipStyle} formatter={value => formatValue(Number(value))} cursor={{ fill: 'rgb(var(--canvas))' }} /></>;
  return <div><div role="img" aria-label={label} className="h-64 w-full min-w-0"><ResponsiveContainer width="100%" height="100%">{variant === 'area' ? <AreaChart data={data} margin={{ top: 15, right: 6, left: 0, bottom: 8 }}><defs>{series.map(item => <linearGradient key={item.key} id={id + item.key} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={item.color} stopOpacity={0.22} /><stop offset="100%" stopColor={item.color} stopOpacity={0.01} /></linearGradient>)}</defs>{axes}{series.map(item => <Area key={item.key} type="monotone" dataKey={item.key} name={item.label} stroke={item.color} strokeWidth={2.5} fill={'url(#' + id + item.key + ')'} isAnimationActive={false} />)}</AreaChart> : <BarChart data={data} margin={{ top: 15, right: 6, left: 0, bottom: 8 }} barGap={5}>{axes}{series.map(item => <Bar key={item.key} dataKey={item.key} name={item.label} fill={item.color} radius={[5, 5, 0, 0]} maxBarSize={26} isAnimationActive={false} />)}</BarChart>}</ResponsiveContainer></div><div className="mt-3 flex flex-wrap justify-center gap-5">{series.map(item => <span key={item.key} className="flex items-center gap-2 text-xs text-muted"><span aria-hidden="true" className="h-2 w-2 rounded-full" style={{ background: item.color }} />{item.label}</span>)}</div></div>;
});
export const DonutChart = memo(function DonutChart({ data, label, formatValue }: { data: { name: string; value: number; color: string }[]; label: string; formatValue: (value: number) => string }) { return <div role="img" aria-label={label} className="h-56 w-full"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={68} outerRadius={92} paddingAngle={3} stroke="none" isAnimationActive={false}>{data.map(item => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip contentStyle={tooltipStyle} formatter={value => formatValue(Number(value))} /></PieChart></ResponsiveContainer></div>; });
export function ChartDataTable({ data, series, xKey, formatValue, caption }: Omit<ChartProps, 'label' | 'formatAxis' | 'variant'> & { caption: string }) { return <details className="mt-4"><summary className="cursor-pointer text-xs font-medium text-muted focus-visible:outline focus-visible:outline-2 focus-visible:outline-indigo">View chart data</summary><div className="mt-3 overflow-auto"><table className="w-full text-left text-xs"><caption className="sr-only">{caption}</caption><thead><tr><th scope="col" className="p-2 text-muted">Period</th>{series.map(item => <th scope="col" key={item.key} className="p-2 text-muted">{item.label}</th>)}</tr></thead><tbody>{data.map((point, index) => <tr key={index} className="border-t border-line"><th scope="row" className="p-2 font-medium text-ink">{point[xKey]}</th>{series.map(item => <td key={item.key} className="p-2 text-ink">{formatValue(Number(point[item.key]))}</td>)}</tr>)}</tbody></table></div></details>; }
