import assert from 'node:assert/strict';
import { http, getAccessToken, setAccessToken, configureAuthentication, refreshAccessToken, clearMutationIntents, ApiError } from '@shared/api';
import { authApi, useAuth } from '@entities/auth';
import { accountApi, useAccounts } from '@entities/account';
import { cardApi } from '@entities/card';
import { transactionApi } from '@entities/transaction';
import { cfoApi } from '@features/ask-cfo';
type Call = { path: string; method: string; headers: Headers; body: unknown; credentials: string | undefined };
const calls: Call[] = [];
let handler: (call: Call) => Promise<Response> | Response = () => json({});
function json(body: unknown, status = 200, headers: Record<string, string> = {}) { return new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json', ...headers } }); }
globalThis.fetch = async (url, init) => { const call = { path: new URL(String(url)).pathname.replace('/api/v1', ''), method: init?.method ?? 'GET', headers: new Headers(init?.headers), body: init?.body ? JSON.parse(String(init.body)) : undefined, credentials: init?.credentials }; calls.push(call); return handler(call); };
async function run() {
 handler = call => call.path === '/auth/refresh' ? json({ message: 'No session' }, 401) : json({ token: 'login-token', fullName: 'Test User', username: 'test-user', recoveryCode: 'private-code', expiresAt: new Date(Date.now() + 900000).toISOString() });
 await useAuth.getState().initialize(); assert.equal(useAuth.getState().status, 'guest');
 await useAuth.getState().login({ usernameOrEmail: 'test-user', password: 'test-password' });
 assert.equal(getAccessToken(), 'login-token'); assert.equal(calls.at(-1)?.headers.get('X-WealthPilot-CSRF'), '1'); assert.equal(calls.at(-1)?.credentials, 'include'); assert.equal(calls.at(-1)?.headers.get('Authorization'), null);
 console.log('PASS real auth uses CSRF, credentials and memory-only access token');
 setAccessToken('expired-token'); let refreshes = 0;
 handler = async call => { if (call.path === '/auth/refresh') { refreshes += 1; await new Promise(resolve => setTimeout(resolve, 15)); return json({ token: 'renewed-token' }); } if (call.headers.get('Authorization') === 'Bearer expired-token') return json({ message: 'Expired' }, 401); return json([]); };
 await Promise.all([accountApi.list(), cardApi.list()]); assert.equal(refreshes, 1); assert.equal(getAccessToken(), 'renewed-token');
 console.log('PASS simultaneous financial 401s share one refresh and retry once');
 configureAuthentication({ refresh: async () => { throw new ApiError('NETWORK', 'offline', 503); }, expired: () => setAccessToken(null) });
 setAccessToken('offline-token'); await assert.rejects(refreshAccessToken('offline-token')); assert.equal(getAccessToken(), 'offline-token');
 let resolveRefresh!: (value: string) => void;
 configureAuthentication({ refresh: () => new Promise(resolve => { resolveRefresh = resolve; }), expired: () => setAccessToken(null) });
 setAccessToken('before-logout'); const refreshing = refreshAccessToken('before-logout'); setAccessToken(null); resolveRefresh('stale-renewed-token'); await refreshing; assert.equal(getAccessToken(), null);
 const logoutCalls = calls.length; setAccessToken('session-to-close'); const pendingRefresh = refreshAccessToken('session-to-close'); handler = () => json({}); const logout = authApi.logout(); await Promise.resolve(); assert.equal(calls.length, logoutCalls); resolveRefresh('rotated-before-logout'); await pendingRefresh; await logout; assert.equal(calls.at(-1)?.path, '/auth/logout');
 console.log('PASS network refresh failure preserves session; late refresh cannot undo logout');
 clearMutationIntents(); let attempt = 0; handler = () => ++attempt === 1 ? json({ message: 'temporary' }, 503) : json({ id: 'created' });
 await assert.rejects(http.command('/accounts', { name: 'One', openingBalancePaise: 500 })); const retryKey = calls.at(-1)?.headers.get('Idempotency-Key'); await http.command('/accounts', { openingBalancePaise: 500, name: 'One' }); assert.equal(calls.at(-1)?.headers.get('Idempotency-Key'), retryKey);
 await http.command('/accounts', { name: 'Two', openingBalancePaise: 500 }); assert.notEqual(calls.at(-1)?.headers.get('Idempotency-Key'), retryKey);
 let resolveWrite!: (value: Response) => void; handler = () => new Promise(resolve => { resolveWrite = resolve; }); const before = calls.length; const first = http.command('/categories', { name: 'Food' }); const second = http.command('/categories', { name: 'Food' }); resolveWrite(json({ id: 'food' })); await Promise.all([first, second]); assert.equal(calls.length - before, 1);
 console.log('PASS ambiguous write retries reuse key and concurrent identical intents submit once');
 const transaction = { id: 'tx', amountPaise: 10000, type: 'expense' as const, categoryId: 'food', date: '2026-10-08', note: 'Lunch', paymentMethodId: 'bank', tags: [] };
 handler = call => call.method === 'GET' ? json(transaction, 200, { ETag: '"revision-7"' }) : json(transaction);
 await transactionApi.get('tx'); const { id: _id, ...input } = transaction; await transactionApi.update('tx', input); assert.equal(calls.at(-1)?.headers.get('If-Match'), '"revision-7"');
 await assert.rejects(transactionApi.update('tx', input), /Reload/);
 handler = call => call.method === 'GET' ? json(transaction, 200, { ETag: '"revision-8"' }) : json({ message: 'Stale version' }, 409);
 await transactionApi.get('tx'); await assert.rejects(transactionApi.update('tx', input), /Stale version/);
 console.log('PASS transaction writes use viewed ETag, reject absent versions and surface conflicts');
 handler = call => call.path === '/cfo/ask' ? json({ id: 'response', conversationId: 'conversation', revision: 1, state: 'awaiting-detail', text: 'What price?', purchase: null, snapshot: {}, quickReplies: null, cards: null, actions: null, decision: { recommendation: 'clarify' } }) : json({ kind: 'remind', reminder: { id: 'reminder', dueDate: '2026-11-08' }, goal: null });
 const cfo = await cfoApi.ask({ requestId: 'stable-request', conversationId: 'conversation', message: 'Buy a phone' }); assert.equal(cfo.purchase, null); assert.deepEqual(cfo.cards, []); assert.equal(cfo.decision?.recommendation, 'clarify');
 await cfoApi.executeAction('server-response', 2, 'server-action-key'); assert.equal(calls.at(-1)?.path, '/cfo/responses/server-response/actions/2'); assert.equal(calls.at(-1)?.body, undefined); assert.equal(calls.at(-1)?.headers.get('Idempotency-Key'), 'server-action-key');
 console.log('PASS CFO clarification preserves nullable purchase and executes server-bound actions');
 let resolveAccounts!: (value: Response) => void; handler = () => new Promise(resolve => { resolveAccounts = resolve; }); useAccounts.getState().reset(); const load = useAccounts.getState().load(); useAccounts.getState().reset(); resolveAccounts(json([{ id: 'old-owner', name: 'Old owner account' }])); await load; assert.deepEqual(useAccounts.getState().items, []);
 console.log('PASS late requests cannot repopulate another user’s cleared financial stores');
 handler = () => new Promise(resolve => { resolveAccounts = resolve; }); setAccessToken('owner-one'); const oldRequest = accountApi.list(); setAccessToken('owner-two'); resolveAccounts(json([])); await assert.rejects(oldRequest, (error: unknown) => error instanceof ApiError && error.code === 'ABORTED');
 handler = () => json({ message: 'signed out' }); await authApi.logout(); assert.equal(calls.at(-1)?.headers.get('X-WealthPilot-CSRF'), '1');
}
run().catch(error => { console.error(error); process.exitCode = 1; });
