import assert from 'node:assert/strict';
import { useGoalPlan, goalApi, plannedGoalStatus, type GoalPlanView } from '@entities/goal';
import { useOverview } from '@entities/overview';
import { setAccessToken } from '@shared/api';
const goals=[{id:'high',name:'High goal',targetPaise:2000000,savedPaise:0,status:'saving',priority:'high',icon:'sparkles'},{id:'low',name:'Low goal',targetPaise:2000000,savedPaise:1900000,status:'saving',priority:'low',icon:'sparkles'}];
const makePlan=(revision:number):GoalPlanView=>({revision,asOf:'2026-10-09T00:00:00Z',plan:{policyVersion:'automatic-goals-v1',liquidPaise:6500000,emergencyProtectedPaise:3000000,livingBufferPaise:1000000,debtProtectedPaise:0,legacyAllocatedPaise:0,automaticPoolPaise:2500000,monthlyCapacityPaise:100000,assumptions:['One shared priority pool'],goals:[{goalId:'high',availablePaise:2000000,remainingPaise:0,canBuyNow:true,waitMonths:0,estimatedBuyDate:'2026-10-09',reason:'ready',targetDateFeasible:null},{goalId:'low',availablePaise:500000,remainingPaise:1500000,canBuyNow:false,waitMonths:15,estimatedBuyDate:'2028-01-09',reason:'saving',targetDateFeasible:false}]}});
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});let handler:(path:string,init?:RequestInit)=>Promise<Response>|Response=path=>json(path.endsWith('/plan')?makePlan(1):goals);globalThis.fetch=async(url,init)=>handler(new URL(String(url)).pathname,init);
async function run(){setAccessToken('automatic-test');useGoalPlan.getState().reset();await useGoalPlan.getState().load();let data=useGoalPlan.getState().data!;assert.equal(data.plan.goals[0].availablePaise,2000000);assert.equal(data.plan.goals[1].availablePaise,500000);assert.equal(useGoalPlan.getState().goals[1].savedPaise,1900000);assert.equal(data.plan.goals.reduce((sum,g)=>sum+g.availablePaise,0),2500000);assert.equal(plannedGoalStatus({...data.plan.goals[0],canBuyNow:false,reason:'debt-first'}).label,'Clear debt first');assert.equal(plannedGoalStatus({...data.plan.goals[1],estimatedBuyDate:null}).label,'No estimate yet');assert.equal(plannedGoalStatus({...data.plan.goals[1],reason:'needs-profile'}).label,'Complete your plan');console.log('PASS server priority order and available amounts override historical saved fields; readiness gates and null estimates are explicit');
let received:unknown;handler=(_path,init)=>{received=JSON.parse(String(init?.body));return json({});};await goalApi.priority('low',{priority:'high',targetDate:null});assert.deepEqual(received,{priority:'high',targetDate:null});console.log('PASS priority editing sends priority and nullable desired date together');
let releaseOld!:(r:Response)=>void;let reads=0;handler=path=>path.endsWith('/plan')?++reads===1?new Promise(resolve=>{releaseOld=resolve;}):json(makePlan(3)):json(goals);const old=useGoalPlan.getState().load();await Promise.resolve();await useGoalPlan.getState().load();releaseOld(json(makePlan(2)));await old;assert.equal(useGoalPlan.getState().data?.revision,3);console.log('PASS older in-flight plans cannot overwrite a newer complete snapshot');
reads=0;handler=path=>path.endsWith('/plan')?new Promise(resolve=>{releaseOld=resolve;}):json(goals);const formerOwner=useGoalPlan.getState().load();await Promise.resolve();useGoalPlan.getState().reset();releaseOld(json(makePlan(4)));await formerOwner;assert.equal(useGoalPlan.getState().data,null);assert.deepEqual(useGoalPlan.getState().goals,[]);console.log('PASS account changes discard pending plan reads and private metadata');
let dashboardReads=0;handler=()=>++dashboardReads===1?new Promise(resolve=>{releaseOld=resolve;}):json({summary:{netWorthPaise:2}});useOverview.getState().reset();const oldDashboard=useOverview.getState().load(true);await Promise.resolve();await useOverview.getState().load(true);releaseOld(json({summary:{netWorthPaise:1}}));await oldDashboard;assert.equal(useOverview.getState().dashboard?.summary.netWorthPaise,2);console.log('PASS refreshed summary supersedes an older financial snapshot');
handler=path=>path.endsWith('/plan')?json({message:'Resource not found'},404):json(goals);await useGoalPlan.getState().load();assert.equal(useGoalPlan.getState().unavailable,true);assert.equal(useGoalPlan.getState().error,null);assert.equal(useGoalPlan.getState().data,null);assert.equal(useGoalPlan.getState().goals.length,2);console.log('PASS missing plan preserves saved goals with no invented readiness');handler=path=>json(path.endsWith('/plan')?makePlan(5):goals);await useGoalPlan.getState().load();assert.equal(useGoalPlan.getState().unavailable,false);assert.equal(useGoalPlan.getState().data?.revision,5);console.log('PASS recovered backend automatically restores planning after refresh');handler=path=>path.endsWith('/plan')?json(makePlan(6)):json({message:'Cannot load goals'},503);await useGoalPlan.getState().load();assert.equal(useGoalPlan.getState().error,'Cannot load goals');console.log('PASS metadata failures remain visible instead of being hidden by fallback');}
run().catch(error=>{console.error(error);process.exitCode=1;});
