import { IS_DEMO } from '@shared/config';
import { useEffect, useId, useRef, useState } from 'react';
import { Bell, X } from 'lucide-react';
import { useNotifications, notificationApi, NotificationItem, unreadNotificationCount } from '@entities/notification';
import { Button, EmptyState, Skeleton, ErrorState, toast } from '@shared/ui';
import { errorMessage } from '@shared/lib';
export function NotificationsPanel() {
  const notices = useNotifications(); const [open, setOpen] = useState(false); const ref = useRef<HTMLDivElement>(null); const buttonRef = useRef<HTMLButtonElement>(null); const id = useId(); const [serverUnread, setServerUnread] = useState<number | null>(null); const unread = IS_DEMO ? unreadNotificationCount(notices.items) : serverUnread ?? unreadNotificationCount(notices.items);
  useEffect(() => { if (IS_DEMO || !notices.loaded) return; let active = true; void notificationApi.unreadCount().then(count => { if (active) setServerUnread(count); }).catch((cause: unknown) => { if (active) toast(errorMessage(cause), 'error'); }); return () => { active = false; }; }, [notices.items, notices.loaded]);
  useEffect(() => { if (!open) return; const outside = (event: PointerEvent) => { if (event.target instanceof Node && !ref.current?.contains(event.target)) setOpen(false); }; const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') { setOpen(false); buttonRef.current?.focus(); } }; document.addEventListener('pointerdown', outside); document.addEventListener('keydown', escape); ref.current?.querySelector<HTMLButtonElement>('[data-close-notices]')?.focus(); return () => { document.removeEventListener('pointerdown', outside); document.removeEventListener('keydown', escape); }; }, [open]);
  const read = async (noticeId: string) => { setOpen(false); try { notices.upsert(await notificationApi.markRead(noticeId)); } catch (cause: unknown) { toast(errorMessage(cause), 'error'); } };
  const readAll = async () => { try { const items = await notificationApi.markAllRead(); items.forEach(notices.upsert); } catch (cause: unknown) { toast(errorMessage(cause), 'error'); } };
  return <div ref={ref} className="relative"><Button ref={buttonRef} variant="ghost" className="relative" aria-label={'Notifications' + (unread ? ', ' + unread + ' unread' : '')} aria-expanded={open} aria-controls={id} onClick={() => setOpen(value => !value)}><Bell size={19} />{unread > 0 && <span aria-hidden="true" className="absolute right-2 top-1.5 h-1.5 w-1.5 rounded-full bg-rose-600" />}</Button>{open && <div id={id} role="dialog" aria-label="Notifications" className="notification-popover"><div className="flex items-center justify-between border-b border-line p-4"><h2 className="font-semibold text-ink">Notifications {unread > 0 && <span className="text-xs text-muted">({unread})</span>}</h2><Button variant="ghost" data-close-notices aria-label="Close notifications" onClick={() => { setOpen(false); buttonRef.current?.focus(); }}><X size={16} /></Button></div><div className="max-h-[60dvh] overflow-y-auto p-2">{notices.error ? <ErrorState message={notices.error} onRetry={() => void notices.load(true)} /> : !notices.loaded ? <Skeleton /> : notices.items.length === 0 ? <EmptyState title="You’re all caught up" description="We’ll keep your important milestones here." /> : notices.items.map(item => <NotificationItem key={item.id} notification={item} onRead={noticeId => void read(noticeId)} />)}</div><div className="border-t border-line p-2"><Button variant="ghost" className="w-full text-xs" disabled={unread === 0} onClick={() => void readAll()}>Mark all as read</Button></div></div>}</div>;
}
