import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Plus } from 'lucide-react';
import { goalApi, useGoals, type GoalInput } from '@entities/goal';
import { Button, Input, Select, Modal, ErrorState, toast } from '@shared/ui';
import { errorMessage } from '@shared/lib';
import { createGoalSchema, goalFormToInput, type CreateGoalValues } from '../model/schema';
function GoalForm({ initial, onCancel, onCreated, onBusy }: { initial?: GoalInput; onCancel: () => void; onCreated: () => void; onBusy: (busy: boolean) => void }) {
  const [error, setError] = useState<string | null>(null);
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<CreateGoalValues>({ resolver: zodResolver(createGoalSchema), defaultValues: { name: initial?.name ?? '', price: initial ? initial.targetPaise / 100 : 0, targetDate: initial?.targetDate ?? '', imageUrl: initial?.imageUrl ?? '', icon: initial?.icon ?? 'sparkles', priority: initial?.priority ?? 'medium' } });
  const submit = async (values: CreateGoalValues) => { onBusy(true); setError(null); try { const goal = await goalApi.create(goalFormToInput(values)); useGoals.getState().upsert(goal); toast('Your new goal is ready.'); onCreated(); } catch (cause: unknown) { setError(errorMessage(cause)); } finally { onBusy(false); } };
  return <form onSubmit={handleSubmit(submit)} noValidate className="space-y-4"><fieldset disabled={isSubmitting} className="space-y-4"><Input label="What are you saving for?" placeholder="A new laptop, a trip, a dream" error={errors.name?.message} {...register('name')} /><Input label="Target price (₹)" type="number" step="0.01" inputMode="decimal" error={errors.price?.message} {...register('price', { valueAsNumber: true })} /><Input label="Target date (optional)" type="date" error={errors.targetDate?.message} {...register('targetDate')} /><div className="grid grid-cols-2 gap-4"><Select label="Icon" {...register('icon')}><option value="sparkles">Sparkles</option><option value="phone">Phone</option><option value="laptop">Laptop</option><option value="plane">Travel</option><option value="headphones">Headphones</option></Select><Select label="Priority" {...register('priority')}><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></Select></div><Input label="Image URL (optional)" placeholder="https://…" error={errors.imageUrl?.message} {...register('imageUrl')} /></fieldset>{error && <ErrorState message={error} />}<div className="flex justify-end gap-2"><Button variant="secondary" onClick={onCancel} disabled={isSubmitting}>Cancel</Button><Button type="submit" busy={isSubmitting}>Create goal</Button></div></form>;
}
export function CreateGoal({ initial, onCreated }: { initial?: GoalInput; onCreated?: () => void }) { const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); return <><Button onClick={() => setOpen(true)}><Plus size={18} />New goal</Button><Modal open={open} onClose={() => { if (!busy) setOpen(false); }} title="Make room for your next goal"><GoalForm initial={initial} onBusy={setBusy} onCancel={() => setOpen(false)} onCreated={() => { setOpen(false); onCreated?.(); }} /></Modal></>; }
