import { FinancialHistory } from '@features/financial-history';
import { IS_DEMO } from '@shared/config';
import { AccountSecurity } from '@features/account-security';
import { useState } from 'react';
import { useUser, ProfileSummary } from '@entities/user';
import { ProfileForm } from '@features/edit-profile';
import { useTheme } from '@features/toggle-theme';
import { PageHeader, Card, AsyncState, Button, Modal, Badge } from '@shared/ui';
import { resetMockData } from '@shared/api';
export function SettingsProfile() { const user = useUser(); const theme = useTheme(state => state.theme); const setTheme = useTheme(state => state.setTheme); const [resetOpen, setResetOpen] = useState(false); return <div className="space-y-6"><PageHeader eyebrow="MAKE IT FEEL LIKE YOURS" title="Your profile & preferences." description="A few details that help your plan fit your life." /><AsyncState loading={!user.profile} error={user.error} onRetry={() => void user.load(true)}>{user.profile && <Card title="Personal details" action={<Badge>{IS_DEMO ? 'Demo profile' : 'Your profile'}</Badge>}><div className="mb-6 border-b border-line pb-6"><ProfileSummary profile={user.profile} /></div><ProfileForm profile={user.profile} /></Card>}</AsyncState><Card title="Appearance"><p className="mb-4 text-sm text-muted">Choose the view that feels right. Your preference stays saved.</p><div className="flex gap-3"><Button variant={theme === 'light' ? 'primary' : 'secondary'} aria-pressed={theme === 'light'} onClick={() => setTheme('light')}>Light</Button><Button variant={theme === 'dark' ? 'primary' : 'secondary'} aria-pressed={theme === 'dark'} onClick={() => setTheme('dark')}>Dark</Button></div></Card>{IS_DEMO && <Card title="Demo workspace"><div className="flex flex-wrap items-center justify-between gap-4"><p className="max-w-lg text-sm leading-relaxed text-muted">Explore with sample data. Restore the starting snapshot whenever you want a fresh walkthrough.</p><Button variant="secondary" onClick={() => setResetOpen(true)}>Reset demo data</Button></div></Card>}{!IS_DEMO && <><AccountSecurity /><FinancialHistory /></>}<Modal open={resetOpen} onClose={() => setResetOpen(false)} title="Restore the demo snapshot?"><p className="mb-5 text-sm leading-relaxed text-muted">This clears the transactions, goals, profile edits, and reminders you added in this demo. Your theme preference stays saved.</p><div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setResetOpen(false)}>Keep exploring</Button><Button variant="danger" onClick={() => { resetMockData(); window.location.reload(); }}>Restore snapshot</Button></div></Modal></div>; }
