import { useMemo, useState } from 'react';
import { useTransactions, monthlyTrend, spendingByCategory, transactionTotals } from '@entities/transaction';
import { useCategories } from '@entities/category';
import { Card, Tabs, CartesianChart, DonutChart, ChartDataTable, AsyncState, EmptyState, type ChartSeries } from '@shared/ui';
import { DEMO_MONTH } from '@shared/config';
import { formatMoney, formatDate } from '@shared/lib';
const series: ChartSeries[] = [{ key: 'incomePaise', label: 'Income', color: '#059669' }, { key: 'expensePaise', label: 'Expenses', color: '#e11d48' }];
const cashflowSeries: ChartSeries[] = [{ key: 'savingsPaise', label: 'Monthly surplus', color: '#6366f1' }];
const compactMoney = (value: number) => formatMoney(value, { compact: true });
export function FinancialCharts() {
  const transactions = useTransactions(); const categories = useCategories(); const [range, setRange] = useState<'6' | '12'>('6');
  const points = useMemo(() => monthlyTrend(transactions.items).slice(-Number(range)).map(point => ({ ...point, label: formatDate(point.month + '-01', { month: 'short' }) })), [transactions.items, range]);
  const breakdown = useMemo(() => spendingByCategory(transactions.items, DEMO_MONTH).map(item => ({ name: categories.items.find(category => category.id === item.categoryId)?.name ?? 'Other', value: item.amountPaise, color: categories.items.find(category => category.id === item.categoryId)?.color ?? '#64748b' })), [transactions.items, categories.items]);
  const expense = transactionTotals(transactions.items, DEMO_MONTH).expensePaise;
  return <AsyncState loading={!transactions.loaded || !categories.loaded} error={transactions.error ?? categories.error} onRetry={() => { void transactions.load(true); void categories.load(true); }}><div className="dashboard-chart-grid"><Card title="Income & expenses" action={<Tabs value={range} onChange={setRange} items={[{ value: '6', label: '6 months' }, { value: '12', label: '12 months' }]} label="Trend period" panelId="income-trend-panel" />}><p className="mb-3 text-xs text-muted">A little perspective on your monthly rhythm.</p><div id="income-trend-panel" role="tabpanel" aria-label="Income and expense trend">{points.length ? <><CartesianChart data={points} series={series} xKey="label" label="Income and expenses over the selected months" formatValue={formatMoney} formatAxis={compactMoney} /><ChartDataTable data={points} series={series} xKey="label" formatValue={formatMoney} caption="Monthly income and expenses" /></> : <EmptyState title="No history yet" description="Add a transaction to begin your financial story." />}</div></Card><Card title="Where your money goes"><p className="text-xs text-muted">October spending by category</p>{breakdown.length ? <><div className="relative"><DonutChart data={breakdown} label="October expense distribution by category" formatValue={formatMoney} /><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><span className="text-[10px] uppercase tracking-wider text-muted">Total spent</span><span className="mt-1 text-lg font-semibold text-ink">{formatMoney(expense)}</span></div></div><div className="space-y-2">{breakdown.slice(0, 4).map(item => <div key={item.name} className="flex items-center justify-between gap-2 text-xs"><span className="flex items-center gap-2 text-muted"><span aria-hidden="true" className="h-2 w-2 rounded-full" style={{ background: item.color }} />{item.name}</span><span className="font-medium text-ink">{formatMoney(item.value)}</span></div>)}</div><details className="mt-4 text-xs"><summary className="cursor-pointer text-muted">View all categories</summary><ul className="mt-2 space-y-2">{breakdown.map(item => <li key={item.name} className="flex justify-between gap-3"><span className="text-muted">{item.name}</span><span className="text-ink">{formatMoney(item.value)}</span></li>)}</ul></details></> : <EmptyState title="A fresh start" description="No expenses recorded this month." />}</Card></div><Card title="Cash flow" className="mt-6" action={<span className="text-xs text-muted">Income minus expenses</span>}><CartesianChart data={points} series={cashflowSeries} xKey="label" label="Monthly cash surplus over the selected period" formatValue={formatMoney} formatAxis={compactMoney} variant="bar" /><ChartDataTable data={points} series={cashflowSeries} xKey="label" formatValue={formatMoney} caption="Monthly cash flow" /></Card></AsyncState>;
}
