import { useEffect, useRef, useState } from 'react';
import { ApiError } from '@shared/api';
import { goalApi, useGoals, useGoalPlan, type Goal, type PlannedGoal } from '@entities/goal';
import { useAuth } from '@entities/auth';
import { useAccounts } from '@entities/account';
import { useCards } from '@entities/card';
import { useTransactions } from '@entities/transaction';
import { Button, Modal, Select, ErrorState, toast } from '@shared/ui';
import { formatMoney, errorMessage } from '@shared/lib';
type Intent={key:string;accountId:string};
export function MarkGoalPurchased({goal,planned}:{goal:Goal;planned:PlannedGoal}) { const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [account,setAccount]=useState('');const [intent,setIntent]=useState<Intent|null>(null);const lock=useRef(false);const accounts=useAccounts();const plan=useGoalPlan();const owner=useAuth(s=>s.identity?.username??'');const storageKey='wealthpilot:purchase:'+owner+':'+goal.id;
 useEffect(()=>{try {const raw=sessionStorage.getItem(storageKey);if(raw){const saved=JSON.parse(raw) as Intent;if(saved.key&&saved.accountId){setIntent(saved);setAccount(saved.accountId);}}}catch{/* In-memory intent remains usable. */}},[storageKey]);
 const eligible=accounts.items.filter(a=>['bank','cash','wallet'].includes(a.type)&&!a.isArchived&&!a.archived&&a.balancePaise>=goal.targetPaise);
 const current=plan.data?.plan.goals.find(g=>g.goalId===goal.id);const ready=!!current?.canBuyNow&&!plan.loading&&!plan.error;const selected=eligible.some(a=>a.id===account);
 const submit=async()=>{if(lock.current)return;if(!intent&&(!ready||!selected)){setError('Refresh the plan and choose a liquid account with the full purchase amount.');return;} lock.current=true;setBusy(true);setError(null);const active=intent??{key:crypto.randomUUID(),accountId:account};setIntent(active);try{sessionStorage.setItem(storageKey,JSON.stringify(active));}catch{/* The same in-memory intent is reused. */}
 try{const item=await goalApi.purchase(goal.id,{paymentAccountId:active.accountId},{idempotencyKey:active.key});try{sessionStorage.removeItem(storageKey);}catch{/* No persistent intent. */}setIntent(null);useGoals.getState().upsert(item);useGoalPlan.getState().invalidate();await Promise.all([useAccounts.getState().load(true),useCards.getState().load(true),useTransactions.getState().load(true),useGoalPlan.getState().load()]);toast(goal.name+' purchase recorded.');setOpen(false);}catch(cause:unknown){setError(errorMessage(cause));if(cause instanceof ApiError&&[400,403,404,422].includes(cause.status)){setIntent(null);try{sessionStorage.removeItem(storageKey);}catch{/* No persistent intent. */}}useGoalPlan.getState().invalidate();void useGoalPlan.getState().load();void useAccounts.getState().load(true);}finally{lock.current=false;setBusy(false);}}
 return <><Button className="w-full" disabled={!planned.canBuyNow&&!intent} onClick={()=>{setError(null);if(!intent)setAccount(eligible[0]?.id??'');setOpen(true);void accounts.load(true);void plan.load();}}>{intent?'Retry pending purchase':'Record purchase'}</Button><Modal open={open} title={'Record '+goal.name+' purchase'} onClose={()=>{if(!busy)setOpen(false);}}><form className="space-y-4" onSubmit={e=>{e.preventDefault();void submit();}}><p className="text-lg font-semibold text-ink">{goal.name} · {formatMoney(goal.targetPaise)}</p><p className="rounded-xl bg-canvas p-3 text-sm text-muted">This records a purchase you make; it does not send money.</p><Select label="Payment account" value={account} disabled={busy||!!intent} onChange={e=>setAccount(e.target.value)} required><option value="">Choose bank, cash or wallet account</option>{eligible.map(a=><option key={a.id} value={a.id}>{a.name} · {formatMoney(a.balancePaise)}</option>)}{intent&&!eligible.some(a=>a.id===intent.accountId)&&<option value={intent.accountId}>Original payment account · pending request</option>}</Select>{!eligible.length&&!intent&&<p className="text-sm text-muted">No single liquid account covers the full price. Record the necessary transfer between your accounts first.</p>}{intent&&<p className="text-xs text-muted">Retry uses the original account and request key. Resolve this pending request before starting another purchase.</p>}{!ready&&!intent&&<p className="text-xs text-muted">Waiting for a current ready-to-buy plan. If your finances changed, this purchase may be blocked.</p>}{error&&<ErrorState message={error}/>}<div className="flex justify-end gap-2"><Button variant="secondary" disabled={busy} onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit" busy={busy} disabled={!intent&&(!ready||!selected)}>{intent?'Retry original request':'Confirm purchase record'}</Button></div></form></Modal></>;
}
